### ISSUE TITLE
PHPDOC: Unusal ending of comment

### ISSUE THREAD

**Issue by rugk** [jonrohan/docs-snippets#10]
This is your PHPDOC snippet:

``` php
/**
 * undocumented function summary
 *
 * Undocumented function long description
 *
 * @param type var Description
 **/
public function FunctionName($value='')
{
    # code...
}
```

However the comment ending as `**/` is quite unusual. Usually (and as defined by [phpdoc](http://phpdoc.org/docs/latest/glossary.html#term-docblocks)) you just end it with `*/`.

It would be nice if you could correct this.

**Comment by rugk** [comment]
Wait no... This is not from your extension: This issue if in `doc_f` (snippet).

Any idea where this snippet comes from? Is it part of the default Atom snippets?

**Comment by jonrohan** [comment]
Interesting, it may be some autocorrect behavior in Atom? Leave this issue open and I'll see if I could track down the cause.

**Comment by rugk** [comment]
Okay, so FYI I've installed [atom-autocomplete-php](https://atom.io/packages/atom-autocomplete-php).

**Comment by jonrohan** [comment]
It looks like this is being completed by `doc_f` snippet from the official langauge-php package https://github.com/atom/language-php/blob/d0f4aca74877c932dd9090421ac6448afd497def/snippets/language-php.cson#L145-L147

I think it's a bug, however should be addressed there.

**Comment by rugk** [comment]
Done.
